apiVersion: v1
kind: Secret
metadata:
  name: ilogtail-secret
type: Opaque
data:
  access_key:   {{ .Values.access_key | b64enc }}  # base64 accesskey id if you want to flush to SLS
  access_key_id:  {{ .Values.access_key_id | b64enc }} # base64 accesskey secret if you want to flush to SLS
